#!/usr/bin/env bash
# bootstrap-worktree.sh — make a fresh git worktree runnable for this project.
#
# The dispatcher runs this after every `git worktree add`. A bare worktree has
# tracked files only: no dependencies, no secrets, no generated code — and no
# tier-1 skill symlinks (gitignored symlinks never materialize in new
# worktrees). This script closes that gap. It must be IDEMPOTENT (it re-runs on
# worktree re-attach) and NON-INTERACTIVE (it runs unattended inside the loop).
#
# Usage: scripts/bootstrap-worktree.sh <target-worktree-path>
set -euo pipefail
WT="${1:?usage: bootstrap-worktree.sh <target-worktree-path>}"

# --- context-specs deterministic section (do not edit or remove) -------------
# Re-create the tier-1 skill/agent symlinks in the new worktree so headless
# skills resolve there. The `context-specs` CLI is installed globally (npm), and
# CONTEXT_SPECS_HOME tells it WHICH harness to link from — the dispatcher
# exports it; a human running this by hand exports their harness repo path.
# Idempotent and fast.
: "${CONTEXT_SPECS_HOME:?export CONTEXT_SPECS_HOME=<path to your harness repo>, or invoke via the harness}"
context-specs link "$WT"
# --- project-specific provisioning below (generated by /env-init) ------------

# Derive the source checkout (developer's clone) from the worktree's git metadata.
# SRC is where the real gitignored files live (secrets, deps, generated code).
SRC_GIT_COMMON=$(git -C "$WT" rev-parse --git-common-dir)
SRC="$(dirname "$SRC_GIT_COMMON")"

# No gitignored runtime files detected at setup time (no .env.example or similar).
# If you add secrets/config files later, copy them here:
#   [[ -f "$SRC/.env" ]] && cp "$SRC/.env" "$WT/.env"
# Copy direction is ALWAYS source → worktree, never the reverse.

# No dependency install step detected (no package.json, Pipfile, Cargo.toml, etc.).
# When you introduce a build system, add the install command here, e.g.:
#   cd "$WT" && npm ci
#   cd "$WT" && uv sync

# No codegen step detected.
# If you add Prisma, protobuf, or similar, generate here:
#   cd "$WT" && npx prisma generate

echo "bootstrap-worktree: done (no project-specific steps needed yet)."
